"
This is a type of function that can be used to agilely change the
behavior of functions. It can automatically check a condition before
executing a function.


"
Class {
	#name : #SCModifier,
	#superclass : #SCFunction,
	#category : #'SmartContract-Model-Generated-Entities'
}

{ #category : #meta }
SCModifier class >> annotation [

	<FMClass: #Modifier super: #SCFunction>
	<package: #'SmartContract-Model-Generated'>
	<generated>
	^ self
]
